spring:
  banner:
    location: classpath:banner.txt

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  cache:
    type: none

services:
  nas:
    base-uri: "http://api.nasdaq.com/api/screener/stocks?tableonly=true&limit=10&exchange=NASDAQ"

cron:
  athena:
    start-time: 0 0 9 * * *

#management:
#  security:
#    enabled: false
#  endpoint:
#    shutdown:
#      enabled: false
#  endpoints:
#    web:
#      exposure:
#        include: '*'

logging:
  file:
    path: ./LOG_PATH_IS_UNDEFINED
    name: demo.log
  level:
    org.springframework: info
    root: info #off, error, warn, info, debug, trace
    com.tcbs: trace
    org.hibernate.SQL: INFO
    org.hibernate.type: INFO
